port: 8080
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create

      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true

  datasource:

    url: jdbc:mysql://localhost:3306/employees_schema

    username: root
    password: 0510208486q

#  sql:
#    init:
#      #      mode: embedded
#      mode: always
#      schema-locations: classpath:data.sql

